version: 2.1
orbs:
  kubernetes: circleci/kubernetes@1.3.0
jobs:
  build:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - kubernetes/install-kubectl
      - run:
          name: Build and Push Mirror Chat Discord Bots
          command: make all
      - run:
          name: Clone Infrastructure Repository
          command: >-
            git config --global user.name "joze144" &&
            git config --global user.password ${GITHUB_PASSWORD} &&
            git clone https://joze144:${GITHUB_PASSWORD}@github.com/mirrorworld-universe/Infrastructure.git ~/Infrastructure &&
            export SERVICE_VERSION=$(git rev-list --count HEAD) &&
            export SERVICE_NAME=mirror-chat-discord-bot &&
            cd ~/Infrastructure/production &&
            kubectl patch --local -f ${SERVICE_NAME}-sato-deployment.yaml -p "{\"spec\":{\"template\":{\"spec\":{\"containers\":[{\"name\":\"${SERVICE_NAME}\",\"image\":\"${DOCKER_REGISTRY}/${SERVICE_NAME}:${SERVICE_VERSION}\"}]}}}}" -o yaml > ${SERVICE_NAME}-sato-deployment.yaml.new &&
            mv ${SERVICE_NAME}-sato-deployment.yaml.new ${SERVICE_NAME}-sato-deployment.yaml &&
            kubectl patch --local -f ${SERVICE_NAME}-zagan-deployment.yaml -p "{\"spec\":{\"template\":{\"spec\":{\"containers\":[{\"name\":\"${SERVICE_NAME}\",\"image\":\"${DOCKER_REGISTRY}/${SERVICE_NAME}:${SERVICE_VERSION}\"}]}}}}" -o yaml > ${SERVICE_NAME}-zagan-deployment.yaml.new &&
            mv ${SERVICE_NAME}-zagan-deployment.yaml.new ${SERVICE_NAME}-zagan-deployment.yaml &&
            kubectl patch --local -f ${SERVICE_NAME}-byrne-deployment.yaml -p "{\"spec\":{\"template\":{\"spec\":{\"containers\":[{\"name\":\"${SERVICE_NAME}\",\"image\":\"${DOCKER_REGISTRY}/${SERVICE_NAME}:${SERVICE_VERSION}\"}]}}}}" -o yaml > ${SERVICE_NAME}-byrne-deployment.yaml.new &&
            mv ${SERVICE_NAME}-byrne-deployment.yaml.new ${SERVICE_NAME}-byrne-deployment.yaml &&
            git add . &&
            git commit -m "bump ${SERVICE_NAME} to ${SERVICE_VERSION}";
            git push
workflows:
  version: 2
  test_and_build:
    jobs:
      - build:
          context: docker
          filters:
            branches:
              only: main
